# Generated by Django 5.2.6 on 2025-09-30 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Event', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VenueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_type', models.CharField(choices=[('marriage_hall', 'Marriage Hall'), ('banquet_hall', 'Banquet Hall'), ('openspace', 'Open Space'), ('conference_room', 'Conference Room'), ('traditional_mandapam', 'Traditional Mandapam'), ('others', 'Others')], default='others', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='venue_types/')),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Venue Type',
                'verbose_name_plural': 'Venue Types',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='Unknown', max_length=255, verbose_name='Full Name')),
                ('mobile', models.CharField(default='Unknown', max_length=20, verbose_name='Mobile Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(default='Unknown', max_length=255)),
                ('phone', models.CharField(default='Unknown', max_length=20)),
                ('email', models.EmailField(blank=True, default='unknown@example.com', max_length=254)),
                ('number_of_people', models.IntegerField(default=0)),
                ('venue_type', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.CharField(blank=True, max_length=255, null=True)),
                ('religious_affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='events.event')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='events.visitor')),
            ],
            options={
                'verbose_name': 'Requisition',
                'verbose_name_plural': 'Requisitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtraRequisitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tables', models.IntegerField(default=0)),
                ('chairs', models.IntegerField(default=0)),
                ('baloons', models.IntegerField(default=0)),
                ('garlands', models.IntegerField(default=0)),
                ('tables_price', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('chairs_price', models.DecimalField(decimal_places=2, default=10, max_digits=8)),
                ('baloons_price', models.DecimalField(decimal_places=2, default=2, max_digits=8)),
                ('garlands_price', models.DecimalField(decimal_places=2, default=5, max_digits=8)),
                ('decor', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=20)),
                ('decor_price', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('band', models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='none', max_length=20)),
                ('band_price', models.DecimalField(decimal_places=2, default=150, max_digits=8)),
                ('DJ', models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='none', max_length=20)),
                ('DJ_price', models.DecimalField(decimal_places=2, default=150, max_digits=8)),
                ('stereo', models.BooleanField(default=False)),
                ('stereo_price', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('lighting', models.BooleanField(default=False)),
                ('lighting_price', models.DecimalField(decimal_places=2, default=80, max_digits=8)),
                ('photography', models.BooleanField(default=False)),
                ('photography_price', models.DecimalField(decimal_places=2, default=200, max_digits=8)),
                ('videography', models.BooleanField(default=False)),
                ('videography_price', models.DecimalField(decimal_places=2, default=250, max_digits=8)),
                ('mic', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requisition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_requisitions', to='events.requisition')),
            ],
            options={
                'verbose_name': 'Extra Requisition',
                'verbose_name_plural': 'Extra Requisitions',
                'ordering': ['-created_at'],
            },
        ),
    ]
