# Generated by Django 5.2.6 on 2025-09-26 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Event', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='Unknown', max_length=255)),
                ('mobile', models.CharField(default='Unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(default='Unknown', max_length=255)),
                ('phone', models.CharField(default='Unknown', max_length=20)),
                ('email', models.EmailField(blank=True, default='unknown@example.com', max_length=254)),
                ('number_of_people', models.IntegerField(default=0)),
                ('tables', models.IntegerField(default=0)),
                ('chairs', models.IntegerField(default=0)),
                ('balloons', models.IntegerField(default=0)),
                ('garlands', models.IntegerField(default=0)),
                ('stereo', models.BooleanField(default=False)),
                ('mic', models.BooleanField(default=False)),
                ('venue_type', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.CharField(blank=True, max_length=255, null=True)),
                ('religious_affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='events.event')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='events.visitor')),
            ],
        ),
    ]
