# Generated by Django 5.2.6 on 2025-09-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('event_type', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
            ],
        ),
    ]
