# Generated by Django 5.2.6 on 2025-09-30 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrarequisitions',
            options={},
        ),
        migrations.RemoveField(
            model_name='extrarequisitions',
            name='DJ_price',
        ),
        migrations.RemoveField(
            model_name='extrarequisitions',
            name='baloons_price',
        ),
        migrations.RemoveField(
            model_name='extrarequisitions',
            name='band_price',
        ),
        migrations.RemoveField(
            model_name='extrarequisitions',
            name='chairs_price',
        ),
        migrations.RemoveField(
            model_name='extrarequisitions',
            name='decor_price',
        ),
        migrations.RemoveField(
            model_name='extrarequisitions',
            name='garlands_price',
        ),
        migrations.RemoveField(
            model_name='extrarequisitions',
            name='lighting_price',
        ),
        migrations.RemoveField(
            model_name='extrarequisitions',
            name='photography_price',
        ),
        migrations.RemoveField(
            model_name='extrarequisitions',
            name='stereo_price',
        ),
        migrations.RemoveField(
            model_name='extrarequisitions',
            name='tables_price',
        ),
        migrations.RemoveField(
            model_name='extrarequisitions',
            name='videography_price',
        ),
        migrations.CreateModel(
            name='VenueRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tables_count', models.IntegerField(default=0)),
                ('chairs_count', models.IntegerField(default=0)),
                ('baloons_count', models.IntegerField(default=0)),
                ('garlands_count', models.IntegerField(default=0)),
                ('decor_type', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=20)),
                ('band_type', models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='none', max_length=20)),
                ('DJ_type', models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='none', max_length=20)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='events.venuetype')),
            ],
            options={
                'verbose_name': 'Venue Inventory',
                'verbose_name_plural': 'Venue Inventories',
            },
        ),
    ]
