# Generated by Django 5.2.6 on 2025-09-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_extrarequisitions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrarequisitions',
            name='DJ_image_basic',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/dj/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='DJ_image_none',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/dj/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='DJ_image_premium',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/dj/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='DJ_image_standard',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/dj/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='band_image_basic',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/band/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='band_image_none',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/band/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='band_image_premium',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/band/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='band_image_standard',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/band/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='decor_image_basic',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/decor/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='decor_image_premium',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/decor/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='decor_image_standard',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/decor/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='lighting_image_basic',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/lighting/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='lighting_image_none',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/lighting/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='lighting_image_premium',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/lighting/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='mic_image_basic',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/mic/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='mic_image_none',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/mic/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='mic_image_premium',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/mic/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='photography_image_basic',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/photography/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='photography_image_none',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/photography/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='photography_image_premium',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/photography/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='stereo_image_basic',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/stereo/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='stereo_image_none',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/stereo/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='stereo_image_premium',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/stereo/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='videography_image_basic',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/videography/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='videography_image_none',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/videography/'),
        ),
        migrations.AddField(
            model_name='extrarequisitions',
            name='videography_image_premium',
            field=models.ImageField(blank=True, null=True, upload_to='extra_items/videography/'),
        ),
        migrations.AlterField(
            model_name='extrarequisitions',
            name='lighting',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('premium', 'Premium')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='extrarequisitions',
            name='mic',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('premium', 'Premium')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='extrarequisitions',
            name='photography',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('premium', 'Premium')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='extrarequisitions',
            name='stereo',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('premium', 'Premium')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='extrarequisitions',
            name='videography',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('premium', 'Premium')], default='none', max_length=20),
        ),
    ]
