# Generated by Django 5.2.6 on 2025-09-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_extrarequisitions_dj_image_basic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuetype',
            name='venue_type',
            field=models.CharField(choices=[('marriage_hall', 'Marriage Hall'), ('banquet_hall', 'Banquet Hall'), ('openspace', 'Open Space'), ('conference_room', 'Conference Room'), ('traditional_mandapam', 'Traditional Mandapam'), ('others', 'Others')], default='others', max_length=255),
        ),
    ]
