# Generated by Django 5.2.6 on 2025-10-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_venuetype_venue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='email',
            field=models.EmailField(default='Unknown', max_length=255, verbose_name='Email Address'),
        ),
    ]
