# Generated by Django 5.2.6 on 2025-10-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_visitor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='fname',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='mobile',
            field=models.CharField(max_length=20, verbose_name='Mobile Number'),
        ),
    ]
